//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Bezrukov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientList
    {
        public int ID { get; set; }
        public string GenderName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public string NumberPhone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateRegistration { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> CountVisit { get; set; }
        public string Tags { get; set; }
    }
}
