//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Bezrukov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientDetails
    {
        public string ClientName { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<decimal> Age { get; set; }
        public Nullable<int> CountTags { get; set; }
        public string GenderName { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
    }
}
